#workflow file for Github Action
name: build_docker
on: [push]
#    push:
#        branches: [master]
jobs:
        update_build:
                runs-on: ubuntu-18.04
                steps:
                      - name: Checkout RHESSysIOinR
                        uses: actions/checkout@v2
                        with:
                                repository: RHESSys/RHESSysIOinR@master
                        
                      - name: Login to DockerHub
                        uses: docker/login-action@v1
                        with:
                                username: ${{ secrets.DOCKER_USERNAME }}
                                password: ${{ secrets.DOCKER_PASSWORD }}

                      - name: Build and Push
                        id: docker_build
                        uses: docker/build-push-action@v2
                        with:
                                push: true
                                tags: lgraup/rhessys
