#workflow file for Github Action
name: build_docker
on: [push]
#    push:
#        branches: [master]
jobs:
        update_build:
                runs-on: ubuntu-18.04
                steps:
                        name: Build Chain ${{ matrix.java-version }}
                        id: build-chain
                        uses: ginxo/github-action-build-chain@BXMSPROD-1025
                        with:
                            definition-file: './definition_file.yml'
                            flow-type: 'single'
                        env:
                            GITHUB_TOKEN: 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
                            #"${{ secrets.GITHUB_TOKEN }}"
                        
                        name: Login to DockerHub
                        uses: docker/login-action@v1
                        with:
                                username: lgraup
                                password: LGdrummer94

                        name: Build and Push
                        id: docker_build
                        uses: docker/build-push-action@v2
                        with:
                                push: true
                                tags: lgraup/rhessys
